/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
import { TransactionObject, BlockType } from "web3/eth/types";
import { Callback, EventLog } from "web3/types";
import { EventEmitter } from "events";
import { Provider } from "web3/providers";

export class DSToken {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  _address: string;
  options: contractOptions;
  methods: {
    balanceOf(src: string): TransactionObject<string>;

    allowance(src: string, guy: string): TransactionObject<string>;

    stop(): TransactionObject<void>;

    setOwner(owner_: string): TransactionObject<void>;

    setAuthority(authority_: string): TransactionObject<void>;

    transfer(dst: string, wad: number | string): TransactionObject<boolean>;

    start(): TransactionObject<void>;

    approve(guy: string, wad: number | string): TransactionObject<boolean>;
    approve(guy: string): TransactionObject<boolean>;

    transferFrom(
      src: string,
      dst: string,
      wad: number | string
    ): TransactionObject<boolean>;

    push(dst: string, wad: number | string): TransactionObject<void>;

    pull(src: string, wad: number | string): TransactionObject<void>;

    move(
      src: string,
      dst: string,
      wad: number | string
    ): TransactionObject<void>;

    mint(wad: number | string): TransactionObject<void>;

    burn(wad: number | string): TransactionObject<void>;

    setName(name_: string | number[]): TransactionObject<void>;

    name(): TransactionObject<string>;
    totalSupply(): TransactionObject<string>;
    decimals(): TransactionObject<string>;
    stopped(): TransactionObject<boolean>;
    owner(): TransactionObject<string>;
    symbol(): TransactionObject<string>;
    authority(): TransactionObject<string>;
  };
  deploy(options: {
    data: string;
    arguments: any[];
  }): TransactionObject<Contract>;
  events: {
    Mint(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    Burn(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    LogSetAuthority(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    LogSetOwner(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    Approval(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    Transfer(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: string[];
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>;
  setProvider(provider: Provider): void;
}
